### ISSUE TITLE
Improvement: The locations should be highlighted in the text and should be clickable. This would look nicer than having a list of the locations at the bottom imo. 

### ISSUE THREAD

**Issue by fredrikmoger** [TheAtlasRepository/Text2Map#58]
See here: 
![image](https://github.com/TheAtlasRepository/Text2Map/assets/51812309/fb7aabe8-9787-4584-a0ee-e3be9d03e577)

Today: 
![image](https://github.com/TheAtlasRepository/Text2Map/assets/51812309/af668ec0-a065-4624-b81b-398968d0f4c6)

**Comment by Eiriksb** [comment]
Fixed in latest release. Places will now appear under the assistant response and be clickable to easily navigate to that place / marker. 
<img width="1400" alt="Screenshot 2024-04-26 at 14 54 20" src="https://github.com/TheAtlasRepository/Text2Map/assets/87980291/397971ca-0f71-4813-868a-1fc6e04abd2b">
